# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171003_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='checked_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='tag_color',
            field=models.CharField(choices=[('teal', 'teal'), ('purple', 'purple'), ('pink', 'pink')], default='teal', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.CharField(choices=[('TODO', 'TODO'), ('Must Be', 'Must Be'), ('Every Day', 'Every Day')], default='TODO', max_length=100),
        ),
    ]
